### ISSUE TITLE
icons overlap in notifications

### ISSUE THREAD

**Issue by devui1085** [js-sugar/angular-zorro#8]
![image](https://user-images.githubusercontent.com/78552334/120685998-c2b99900-c4b5-11eb-82d0-bcc04367362f.png)

Icons overlapping each other in notification component

**Comment by mehrta** [comment]
Fixed.
Following lines was added to Appomponent:

  ngOnInit(): void {
    this.nzConfigService.set('notification', { nzDirection: 'rtl' });
  }


![notif](https://user-images.githubusercontent.com/34556599/124347865-9c157d80-db9b-11eb-904f-4c0360702a67.PNG)
